# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70e174627927e1a5a3d50e72d287b12fc59d41763c525433ff336073853f5889f6f70e63b99f38dfdf331734370bfd5f23d21b2dd40ac773cd0df176f75be586

test:
  secret_key_base: 54cba07f4b72f6994eada527b06ae0afc0dedfb7f1abcff182433a16a74f2975b48aab170aa0b8c2d5c04eacd93d8884071500a5c6d61a96ff2c3e94fcf2cac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
